from Stack import Stack
myStack=Stack(5)

print(myStack.isEmptyStack())
print(myStack.isFullStack())
print(myStack.pop())
myStack.push(10)
myStack.push(20)
myStack.push(30)
myStack.push(40)
print(myStack.stack)
myStack.pop()
print(myStack.stack)
print(myStack.top())
print(myStack.size())
myStack.push(50)
myStack.push(60)
myStack.push(70)
print(myStack.isEmptyStack())
print(myStack.isFullStack())